### ISSUE TITLE
"This" replacement rule triggered when using enum with the same value as class name

### ISSUE THREAD

**Issue by ghost** [cogneco/magic#103]
``` ooc
SomeEnum: enum {
    Foobar
    Moobar
}
```

``` ooc
Foobar: class {
    c ::= SomeEnum Foobar
...
}
```

magic reports:

> [y, x]......replace 'Foobar' with 'This'

**Comment by thomasfanell** [comment]
This would be easy to fix if the enum is in the same file, but if it's not, there is no solid way to tell that `SomeEnum` is in fact an enum. Stuff like this will be much easier to fix in the new version of magic, where we will have proper means to look things up.

If I find a good way to fix this in the current version, I will, but in the mean time, all of us have to critically evaluate what magic is telling us, just like you did here.

**Comment by davidhesselbom** [comment]
I think, but I'm not entirely sure, that this is the only time we have two consecutive words that start with a capital letter. What if magic were to suppress this rule in those special cases?

**Comment by thomasfanell** [comment]
This is a somewhat hacky solution based on @davidhesselbom's idea, but it seems to work for now.
