### ISSUE TITLE
Ignore empty brackets in class declarations.

### ISSUE THREAD

**Issue by ghost** [cogneco/magic#109]
``` ooc
SomeClass: class extends AnotherClass {}
```

> [3, 41].......missing space after separator '{'

Empty brackets can't be omitted when we want to declare an empty class, so magic should ignore them for now.

**Comment by thomasfanell** [comment]
Why is this kind of code even allowed in? Why have empty classes?

**Comment by davidhesselbom** [comment]
Well, that's a good question. I think it was added to get around a limitation that prevented us from creating an array of a generic type for a specific `T`. We may be able to get rid of it now...

**Comment by ghost** [comment]
I don't understand, what's wrong with an empty class and why it shouldn't be allowed ?

**Comment by davidhesselbom** [comment]
I think we should allow empty classes (although I don't know what they're for, and although I think the particular class that gave rise to this issue may not even be necessary), and I think rock should allow us to omit the brackets, but it doesn't. Making magic ignore empty brackets for empty classes seems like the easiest way to get this "fixed".

**Comment by davidhesselbom** [comment]
Was this fixed already?

**Comment by ghost** [comment]
Can we agree that we should write 
`SomeClass: class extends AnotherClass { }` (with space)
instead of `SomeClass: class extends AnotherClass {}` and close this issue ?
@marcusnaslund @thomasfanell ?

**Comment by thomasfanell** [comment]
I thought this was fixed... must have forgotten about it... sorry about that. I'll see if I can squeeze in a fix today. `magic` should allow both cases?

**Comment by ghost** [comment]
Great, thanks.
I don't really know about the style, @marcusnaslund ?

**Comment by marcusnaslund** [comment]
This is terrible either way, but let's agree on one way to do it, not two. If `{ }` works I'm OK with just going with that.

**Comment by ghost** [comment]
It works with space now. @thomasfanell you can close this issue if you are happy with this too

**Comment by thomasfanell** [comment]
I am happy with this, but I can't close the issue (no access yet)
