### ISSUE TITLE
Codehance

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/magic#117]
It would be fun to let this project be called codehance instead, especially when we reach a point where it can be trusted to fix some things automatically with no user interaction.

**Comment by thomasfanell** [comment]
I vote yes! @simonmika, what do you say?

**Comment by davidhesselbom** [comment]
So... apparently this isn't supposed to stay at being a code quality tool but something much larger. For such a project, "Codehance" isn't a very good name.
