### ISSUE TITLE
All SDK folders are currently ignored

### ISSUE THREAD

**Issue by thomasfanell** [cogneco/magic#16]
It should only ignore the ooc language sdk, not any sdk folder.

**Comment by davidhesselbom** [comment]
Solution: only ignore `sdk` folders located at `source/sdk` relative to a `sdk.use` file. If no `sdk.use` file is found, ignore no `sdk` folder.

**Comment by thomasfanell** [comment]
This will be solved by using an ignore file, similar to .gitignore. Each project may have this ignore file in its root folder and it should contain relative search paths. I should have a solution up by the end of today.
