### ISSUE TITLE
.. is an operator and should be surrounded by spaces

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/magic#20]
``` ooc
for (i in 0..length - 1)
```

looks more like

``` ooc
for (i in (0..length) - 1)
```

than

``` ooc
for (i in 0..(length - 1))
```

and magic complains about `length-1` but not `0..length`.

**Comment by thomasfanell** [comment]
.. is the range operator (not sure if that is the official name though), but it is considered to be an operator nonetheless, and it is excluded from the operator spacing rules.

**Comment by davidhesselbom** [comment]
> it is excluded from the operator spacing rules

Should it be?

**Comment by thomasfanell** [comment]
Good question. `for (i in 0..length - 1)` looks rather weird. I would personally always write this as `for (i in 0..(length - 1))`. Maybe that should be a rule instead, to enforce parentheses for operands that are non-literal?

**Comment by davidhesselbom** [comment]
No, that's going to turn ooc into Lisp :P

**Comment by simonmika** [comment]
It is a binary operator with low precedence and it should therefore be surrounded by space.

**Comment by davidhesselbom** [comment]
I guess that settles it.
