### ISSUE TITLE
Keyword extern

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/magic#33]
`extern` is a keyword and should be surrounded by spaces.

**Comment by thomasfanell** [comment]
So are get/set. Should we require spaces for those too?

**Comment by thomasfanell** [comment]
unmangled?

**Comment by davidhesselbom** [comment]
Sure, why not? Make sure you don't raise warnings for function names that contain `get` and `set`, though.

**Comment by thomasfanell** [comment]
you mean like getX(), setY() etc? That can't happen :)
