### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/magic#4]
Allow configuration. To start with, make leading tab/spaces check optional, in case the user prefers using spaces for indentation.

**Comment by simonmika** [comment]
I actually don't agree, I think the tool should not support any coding style. The purpose of the tool is to strictly enforce THE style. I strive after a situation where there only is one valid style for the language. Much like how it is for Go.

 The only option I imagine necessary is paths not to check for use with imported legacy code.

**Comment by davidhesselbom** [comment]
Alright then. Should be an easy hack for those who prefer spaces, though, so no biggie. Closing...
