### ISSUE TITLE
Path to node

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/magic#62]
On Travis, the path to node isn't the same as on a Ubuntu system (maybe). Previously, releases of magic have hard-coded the path to node in the [shebang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29) part (`#!`) as whatever path node was located at on the system where the release was built, which is demonstrably bad for portability.

A solution to this is to replace the path to node with the path to env, like this: `#!/usr/bin/env node`. The system will then find node, wherever it is installed, and use that.

I'm not sure what happens if node isn't installed at all, but we should be able to count on that `env` is located at `/usr/bin/env`, at least.

**Comment by thomasfanell** [comment]
The install script is now using your suggestion (and it seems to work fine here).
