### ISSUE TITLE
Magic complains about the pre increment ++ operator.

### ISSUE THREAD

**Issue by ghost** [cogneco/magic#72]
``` ooc
++result
```

magic:

> [].....missing space before and after operator '+'
> [].....missing space before and after operator '+'

**Comment by thomasfanell** [comment]
I'll fix.

**Comment by thomasfanell** [comment]
Fixed in v0.1.9.

**Comment by davidhesselbom** [comment]
And when will v0.1.9 be released? :)

**Comment by thomasfanell** [comment]
I wanted to implement the Indent rule before I did, but now i'm busy with Kean, so I can create 0.1.9 without it

**Comment by davidhesselbom** [comment]
Alright, go ahead. I'd much rather have frequent, small releases where not much changes than completed features waiting to be released.
