### ISSUE TITLE
Too many consecutive characters

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/magic#78]
In the following code, spaces are used to align things nicely:

``` ooc
XK_Home                         : extern const ULong
XK_Left                         : extern const ULong
XK_Up                           : extern const ULong
XK_Right                        : extern const ULong
XK_Down                         : extern const ULong
XK_Prior                        : extern const ULong
XK_Page_Up                      : extern const ULong
XK_Next                         : extern const ULong
XK_Page_Down                    : extern const ULong
XK_End                          : extern const ULong
XK_Begin                        : extern const ULong
```

In order to make magic happy, the spaces need to be removed:

``` ooc
XK_Home : extern const ULong
XK_Left : extern const ULong
XK_Up : extern const ULong
XK_Right : extern const ULong
XK_Down : extern const ULong
XK_Prior : extern const ULong
XK_Page_Up : extern const ULong
XK_Next : extern const ULong
XK_Page_Down : extern const ULong
XK_End : extern const ULong
XK_Begin : extern const ULong
```

but it should be obvious the first version is neater than the second. How do we handle this kind of case?

**Comment by thomasfanell** [comment]
Off the top of my head: magic checks the position of the separator token, in this case `:`, if it finds that it's the same for two or more consecutive statements, it could make an educated guess that this is intentional formatting and leave it alone. 

Edit: By position, I mean column (in case that wasn't obvious)

**Comment by thomasfanell** [comment]
In the final product, you should be able to turn on/off checks via specialized comments that acts as preprocessor directives, much like `#pragma warning(disable : warning-id)`.

**Comment by davidhesselbom** [comment]
I just discovered I can reduce all this to

``` ooc
XK_Home,
XK_Left,
XK_Up,
XK_Right,
XK_Down,
XK_Prior,
XK_Page_Up,
XK_Next,
XK_Page_Down,
XK_End,
XK_Begin : extern const ULong
```

(or at least, it _seems_ to work) so it's not actually an issue after all. Closing.

**Comment by thomasfanell** [comment]
Hmm, that's neat.
