### ISSUE TITLE
Redundant type information bug

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/magic#83]
``` ooc
eglCreatePbufferSurface: extern func (display: Pointer, config: Pointer, attridList: Int*) -> Pointer
eglCreateContext: extern func (display: Pointer, config: Pointer, sharedContext: Pointer, attribList: Int*) -> Pointer
```

magic warns that 

```
[191, 90].....redundant type information, reduce to (display, config, attridList, Int: Pointer)
[192, 107]....redundant type information, reduce to (display, config, sharedContext, attribList, Int: Pointer)
```

Please start using tests to verify that magic works as expected.

**Comment by davidhesselbom** [comment]
Here's another one:

``` ooc
    draw: static func (positions: Float*, count: Int, dimensions: Int) {
```

The warning?

```
[32, 70]......redundant type information, reduce to (positions, Float, count, dimensions: Int)
```

Not sure what your last fixes did, but they sure broke something :blush:

**Comment by thomasfanell** [comment]
I am developing a test framework for version 0.2. It will however not be implemented in the alpha versions. So for this version, simplified manual tests will be employed. This particular bug was obviously a stupid oversight on my part. :-)

**Comment by davidhesselbom** [comment]
We are all guilty of "stupid oversights" from time to time &mdash; that's exactly why you should have tests.

**Comment by davidhesselbom** [comment]
So... good luck with the framework! :)
